# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52d814f58299010cc473baaf028681e15a760439974bc654ec1a624173de9b40d924c15bbe389a1a45d1c9e8df5a6f62a93cad921d8686ebacf46d954835a3d9

test:
  secret_key_base: 2e620080c1cfabc73a05db07d8ebb92998b36dcf54ba02968168cade571d8b18f63a0f0c8de3f9fa031a1870fa278ea265be3df077807bf5bdeb57dfd34028c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
